@PaceCalculator.API_HostAddress = http://localhost:5156

GET {{PaceCalculator.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{PaceCalculator.API_HostAddress}}/estimate?distanceMeters=20000
Accept: application/json
Content-Type: application/json

[
  { "distanceMeters": 5000, "timeSeconds": 1500 },
  { "distanceMeters": 10000, "timeSeconds": 3100 }
]

###